import './globals.css'

import clsx from 'clsx'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): React.JSX.Element {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          'flex min-h-[90vh] items-center justify-center p-[24px]',
        )}
      >
        {children}
      </body>
    </html>
  )
}
